project:
  type: website
  output-dir: _site
  preview:
    port: 8681
    browser: false
    watch-inputs: false
  render:
    - "*.qmd"
    - "notebooks/01_split_data.ipynb"
    - "notebooks/02_scoping.ipynb"
    - "notebooks/03_eda_v2.ipynb"
    - "notebooks/04_run_validation_experiments.ipynb"
    - "notebooks/05_get_best_validation_experiment.ipynb"
    - "notebooks/06_evaluate.ipynb"
    - "notebooks/07_inference.ipynb"
    - "notebooks/12_validate_data.ipynb"
    - CODE_OF_CONDUCT.md
    - LICENSE.md

website:
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  open-graph: true
  title: Credit-Card Churn Modeling and Targeting
  site-url: https://edesz.github.io/credit-card-churn
  repo-url: https://github.com/edesz/credit-card-churn
  repo-actions: [edit, source, issue]

  page-footer:
    left:
      - text: "&#169; 2026 edesz"
        href: https://github.com/edesz
        target: _blank
    center:
      - text: "Code of Conduct"
        href: CODE_OF_CONDUCT.md
      - text: License
        href: LICENSE.md
    right: "Built with ︎♥️ & [Quarto](https://quarto.org), based on [EarthdData Cloud Cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/)"
  cookie-consent:
    type: express
    style: simple
    prefs-text: "Cookie Preferences"

  sidebar:
    title: Churn Insights
    pinned: true
    aligned: center
    tools:
      - icon: globe
        href: https://edesz.github.io/credit-card-churn
        text: "Homepage"
        target: _blank
      - icon: github
        href: https://github.com/edesz/credit-card-churn
        target: _blank
    style: "docked"
    search: true
    collapse: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - section: "Overview"
        contents:
          - text: Business Problem
            href: references/overview/00_overview.qmd
          - text: Approach
            href: references/overview/01_approach.qmd
          - text: Team Member Contributions
            href: references/overview/02_team_contributions.qmd
      - section: "Project Scoping"
        contents:
          - text: Problem Understanding
            href: references/scope/01_problem_understanding.qmd
          - text: Costs
            href: references/scope/02_costs.qmd
          - text: Goals
            href: references/scope/03_goals.qmd
          - text: Actions
            href: references/scope/04_actions.qmd
          - text: Data
            href: references/scope/05_data.qmd
          - text: Analysis
            href: references/scope/06_analysis.qmd
      - section: "Data Analysis"
        contents:
          - text: Data Retrieval and Splitting
            href: notebooks/01_split_data.ipynb
          - text: Analysis for Scoping
            href: notebooks/02_scoping.ipynb
          - text: EDA
            href: notebooks/03_eda_v2.ipynb
      - section: ML Development
        contents:
          - text: ML Validation
            href: notebooks/04_run_validation_experiments.ipynb
          - text: Best Validation Experiment
            href: notebooks/05_get_best_validation_experiment.ipynb
          - text: ML Evaluation
            href: notebooks/06_evaluate.ipynb
          - text: ML Inference
            href: notebooks/07_inference.ipynb
      - section: "Data Validation"
        contents:
          - text: Data Validation Model
            href: notebooks/12_validate_data.ipynb

execute:
  echo: true
  output: true
  enabled: false
  freeze: true

format:
  html:
    grid:
      sidebar-width: 350px
    smooth-scroll: true
    code-overflow: wrap
    code-fold: false
    code-link: true
    code-background: true
    code-copy: true
    section-divs: false
    toc: true
    toc-depth: 5
    toc-expand: true
    link-external-icon: true
    link-external-newwindow: true
    theme:
      dark: [darkly, docs/styles/dark.scss]
      light: [flatly, docs/styles/light.scss]
