# ============================== Project metadata ==============================

[project]
name = "cc-churn"
version = "0.1.0"
description = "Use ML to find customers at risk of churning, for client intervention."
authors = [{name = "edesz"}]
requires-python = ">= 3.10"
# These are the PyPI dependencies, added with: pixi add --pypi PACKAGE_NAME
dependencies = []

[tool.pixi.workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

# location where the build tool should find custom modules to be tested
[tool.setuptools.packages.find]
where = ["src"]

# ============================= Conda dependencies =============================

[tool.pixi.dependencies]
python = "3.12.10.*"
# use pyarrow from conda-forge in order to get required C dependencies
numpy = "*"
pyarrow = "*"
python-dotenv = "*"
openpyxl = "*"
boto3 = "*"
pandas = "*"
pandera-pandas = "*"
pandera-hypotheses = "*"
matplotlib = "*"
seaborn = "*"
altair = "*"
scikit-learn = "*"
metaflow = "*"
xgboost = "*"
joblib = "*"
shap = "*"

# ================== Make this project available as a package ==================

[tool.pixi.pypi-dependencies]
cc-churn = { path = ".", editable = true }

# ========= Specify non-essential dependencies in features ========

[tool.pixi.feature.notebooks.dependencies]
# create a notebooks feature for exploration
ipykernel = "*"
ipywidgets = "*"
jupyterlab = "*"
jupysql = "*"
jupytext = "*"
jupyter_server_ydoc = "*"
jupyter_server_fileid = "*"
jupyter-ruff = "*"
nbconvert = "*"
nbclassic = "*"
panel = "*"
toml = "*"

[tool.pixi.feature.nbrunner.dependencies]
# create a notebook runner feature to perform data or ML validation
ipykernel = "*"
nbconvert = "*"
nbformat = "*"
pytz = "*"
papermill = "*"
typer = "*"

[tool.pixi.feature.test.dependencies]
# create a test feature
ipykernel = "*"
moto = "*"
pytest = "*"
coverage = "*"
pytest-html = "*"

# ========= Specify non-essential dependencies in environments ========

[tool.pixi.environments]
# create environments that use features created above
default = { solve-group = "default" }
# notebooks env inherits default feature and notebooks feature to run jlab
notebooks = { features = ['default', "notebooks"], solve-group = "notebooks" }
nbrunner = { features = ["default", "nbrunner"], solve-group = "nbrunner" }
# test env inherits default feature and unit-test feature to run pytest
test = { features = ["default", "test"], solve-group = "default" }

# ========================== Define tasks (shortcuts) ==========================

[tool.pixi.feature.notebooks.tasks]
# run development tasks for the notebooks feature
jlab = { cmd = """
    jupyter lab""", depends-on = [], description="""\
    Launch Jupyterlab\
    """, default-environment = "notebooks" }

[tool.pixi.feature.test.tasks]
# run unit-test tasks with Pytest for the test feature
test = { cmd = """
    coverage run -m pytest &&
    coverage report -m &&
    coverage html && coverage xml
    """, description="""\
    Run unit tests with Pytest\
    """, default-environment = "test" }

[tool.pixi.feature.nbrunner.tasks]
# programmatically run ML validation experiments for the nbrunner feature
mlval = { cmd = """
    python3 papermill_runner.py 05
    """, description="""\
    Run ML Validation experiments with Metaflow\
    """, default-environment = "nbrunner" }
# programmatically run data validation for the nbrunner feature
dval = { cmd = """
    python3 papermill_runner.py 13
    """, description="""\
    Validate customer data with Pandera\
    """, default-environment = "nbrunner" }
