[pytest]
pythonpath = .
testpaths = tests
addopts = --html=tests/test-logs/testreport.html
    --self-contained-html
    --junitxml=tests/test-logs/testreport.xml
    -ra -vv -q
    --tb=short
filterwarnings =
    ignore::DeprecationWarning
