---
Title: Business Problem
author:
  - name: "edesz"
    orcid: "0000-0001-9039-5496"
    attributes:
      github: "edesz"
date: 2025-04-24
language:
  title-block-published: "Last Updated"
---

# Business Problem {#business-problem}

In this project, our team worked with a manager of the credit card division at a bank who was concerned about an increasing number of customers leaving the credit card division. The client reached out to our team for help identifying customers at risk of canceling their credit card services in the future.

The client provided us with a random sample of ~10,100 customers' behavioural and demographic attributes from the last 12-16 months and outcome during a later period in a `*.xlsx` file. The outcome was whether the customers churned or did not churn.

The credit card management team would reach out to customers that we identified as being at risk of churning with offers to try to get them to revert their decision to cancel their credit card services at the bank.
